version: '3'
services:
  tmdb-proxy-api:
    build:
      dockerfile: Dockerfile.dev
      context: .
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
    ports:
      - 8080:8080
    environment:
      - LOGPATH=/usr/app/logs
    env_file:
      - .env.development